### ISSUE TITLE
Incompatible with Device.BeginInvokeOnMainThread()?

### ISSUE THREAD

**Issue by knocte** [winstongubantes/MatchaBackgroundService#1]
In the README file you say:

> Keep in mind that the plugin was not design to communicate with UI thread

However, I was wondering: what's the issue about calling to Device.BeginInvokeOnMainThread() at the end of the StartJob() method? Would that not work?

P.S.: great work on conceptualizing this lib btw!

**Comment by winstongubantes** [comment]
Hi @knocte , Thank you

I think there is no need to wrap the StartJob method with BeginInvokeOnMainThread, what remember with BeginInvokeOnMainThread  method is,  it used to make the expression run on the UI thread. Just make it a simple method call. Hope it helps :)

**Comment by knocte** [comment]
> there is no need to wrap the StartJob method with BeginInvokeOnMainThread

I never said to wrap the StartJob method with BeginInvokeOnMainThread, I said to call BeginInvokeOnMainThread inside the StartJob method, at the end, when you already have the results of your background execution.

**Comment by winstongubantes** [comment]
@knocte there is no need to use BeginInvokeOnMainThread inside the StartJob you are trying to  make the expression run on the UI thread, StartJob supposed to be runned on the background thread.

**Comment by knocte** [comment]
But after the background thread has finished, there's a need to notify the UI thread to do stuff (otherwise what's the purpose of the background thread if not other than to have an effect on what the user sees at some point?).

**Comment by winstongubantes** [comment]
Hi @knocte, that is the limitation i discussed in "Quirks and Limitation" section, The purpose of this plugin is to simplify the background execution per platform, just like how facebook ans twitter handle the aggregation of content in the background.

 But If you want to dig deeper about advance Background Service per each platform you can check on this links below:
Android BackgroundServices [LINK](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/services/)
iOS BackgroundServices [LINK](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/backgrounding/introduction-to-backgrounding-in-ios)

Hope it helps.

**Comment by knocte** [comment]
> Hi @knocte, that is the limitation i discussed in "Quirks and Limitation" section

I know, that's why I started this issue saying "In the README file you say:".
So this issue is to discuss why is there this limitation? can you elaborate on how this is a limitation? what happens if you just use BeginInvokeOnMainThread at the end of the StartJob method? does it crash? what do you exactly mean with it being a limitation?

**Comment by winstongubantes** [comment]
Hi @knocte , the limitation being not able to communicate with UI Thread (so when using BeginInvokeOnMainThread  which would actually call RunOnUiThread method for Android and InvokeOnMainThread for iOS which may cause erratic behavior on your periodic task ). If you implement your own background services per each platform that is one of the limitation as discuss here

Android BackgroundServices [LINK](https://docs.microsoft.com/en-us/xamarin/android/app-fundamentals/services/)
iOS BackgroundServices [LINK](https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/backgrounding/introduction-to-backgrounding-in-ios)

you can always implement your own backgroundservice or you can tweak this project to, If this is plugin does not satisfy the stuff that you need.

The purpose really of this plugin is to simplify the backgrounding stuff. Hope it Helps
