### ISSUE TITLE
Not run when app closed!

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [winstongubantes/MatchaBackgroundService#12]
Thank for you plugin!
It's work fine when app sleep. Not run when app closed!

**Comment by winstongubantes** [comment]
@nguyenthanhliemfc as discussed in [Quirks and Limitation](https://github.com/winstongubantes/MatchaBackgroundService#quirks-and-limitation)  there is a background execution limits imposed by operating system both Android(starting Oreo) and iOS when app is being closed.

**Comment by nguyenthanhliemfc** [comment]
Thanks you

**Comment by candidodmv** [comment]
@winstongubantes but answer me a doubt: The real background(when the app is entire closed, not in second plan) the tasks will be invoked in any time? I want means will be run, but when is that what you are calling as "Limitation" ? or will never be run any task? Thanks
