### ISSUE TITLE
Sometime error when start() on UWP!

### ISSUE THREAD

**Issue by nguyenthanhliemfc** [winstongubantes/MatchaBackgroundService#14]
Sometime error:
"Cannot create a file when that file already exists. (Exception from HRESULT: 0x800700B7)"

**Comment by nguyenthanhliemfc** [comment]
Anyone get the same issue like me?

**Comment by winstongubantes** [comment]
do you have a sample project that replicate this?

**Comment by nguyenthanhliemfc** [comment]
I have try Unregister before Register and it solved!

**Comment by winstongubantes** [comment]
great, well close this one then

**Comment by t30n3** [comment]
> 
> 
> I have try Unregister before Register and it solved!

Hi,
I am encountering the same issue: how did you solve it?

Thanks in advance,
Matteo

**Comment by nguyenthanhliemfc** [comment]
@t30n3 You can try Unregister OnStart and Register again

**Comment by t30n3** [comment]
> 
> 
> @t30n3 You can try Unregister OnStart and Register again

Do you have an example? I cannot find any Register or Unregister method.

Thanks in advance,
Matteo

**Comment by nguyenthanhliemfc** [comment]
@t30n3 In document of this plug. In Register guide, you can try Stop and Start again

**Comment by t30n3** [comment]
Ok, this seems to solve the issue.

Thank you very much,
Matteo
