### ISSUE TITLE
Service is not running in sleeping mode

### ISSUE THREAD

**Issue by anatolii-bohdanov** [winstongubantes/MatchaBackgroundService#17]
Tried Matcha.BackgroundService demo project on Android 9.0 and 8.1.

**Comment by ndastur** [comment]
Just had a look into the source and as far as I can see this creates some sort of internal timer rather than using the true Android periodic worker. So I suspect this will not work as expected?

**Comment by winstongubantes** [comment]
@ReDERO @ndastur it is explained in [quirks-and-limitation](https://github.com/winstongubantes/MatchaBackgroundService#quirks-and-limitation), Starting with Android Oreo it has already introduced the background execution limits similar to iOS background time limits assuming the app is in background mode or app is closed or minimized.

**Comment by ndastur** [comment]
Thanks @winstongubantes. True. But this was really never the way to do periodic tasks even before the Oreo restrictions. As a suggestion look at the Alarm Manager or Job Worker. Hope this helps.
