### ISSUE TITLE
One question!

### ISSUE THREAD

**Issue by angelru** [winstongubantes/MatchaBackgroundService#6]
Great plugin! it works very good!

it's possible that work when app is closed? or i have i create the independent service for each platform?

**Comment by winstongubantes** [comment]
Hi @angelru, when the app is closed  it will still run in the background, however there were time limits that the OS imposed. e.g. The iOS only allows 3 minutes to run your background service and for Android beginning on Oreo they are now have limit to background execution . So basically this plugin a simple way of isolating an interval method call through background process and improve the user experience.
